/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TreasureChessEscrow {
  export type GameStruct = {
    gameId: BytesLike;
    player1: AddressLike;
    player2: AddressLike;
    wagerAmount: BigNumberish;
    totalPot: BigNumberish;
    status: BigNumberish;
    result: BigNumberish;
    createdAt: BigNumberish;
    lastMoveAt: BigNumberish;
    timeoutSeconds: BigNumberish;
  };

  export type GameStructOutput = [
    gameId: string,
    player1: string,
    player2: string,
    wagerAmount: bigint,
    totalPot: bigint,
    status: bigint,
    result: bigint,
    createdAt: bigint,
    lastMoveAt: bigint,
    timeoutSeconds: bigint
  ] & {
    gameId: string;
    player1: string;
    player2: string;
    wagerAmount: bigint;
    totalPot: bigint;
    status: bigint;
    result: bigint;
    createdAt: bigint;
    lastMoveAt: bigint;
    timeoutSeconds: bigint;
  };
}

export interface TreasureChessEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_WAGER"
      | "MIN_WAGER"
      | "PLATFORM_FEE_BPS"
      | "backendSigner"
      | "calculatePayout"
      | "cancelGame"
      | "claimTimeoutWin"
      | "createGame"
      | "defaultTimeoutSeconds"
      | "emergencyRefund"
      | "games"
      | "getGame"
      | "isTrustedForwarder"
      | "joinGame"
      | "markDisputed"
      | "owner"
      | "platformVault"
      | "recordMove"
      | "renounceOwnership"
      | "rescueGameFunds"
      | "resolveDispute"
      | "setBackendSigner"
      | "setDefaultTimeout"
      | "setPlatformVault"
      | "submitResult"
      | "totalGamesCreated"
      | "totalPlatformFees"
      | "transferOwnership"
      | "trustedForwarder"
      | "usdc"
      | "usedSignatures"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendSignerUpdated"
      | "DefaultTimeoutUpdated"
      | "DisputeResolved"
      | "GameCancelled"
      | "GameCompleted"
      | "GameCreated"
      | "GameDisputed"
      | "GameJoined"
      | "OwnershipTransferred"
      | "PlatformVaultUpdated"
      | "TimeoutClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_WAGER", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_WAGER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backendSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGame",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeoutWin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createGame",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTimeoutSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getGame", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "joinGame", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "markDisputed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordMove",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueGameFunds",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGamesCreated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usedSignatures",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_WAGER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_WAGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeoutWin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultTimeoutSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueGameFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGamesCreated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedSignatures",
    data: BytesLike
  ): Result;
}

export namespace BackendSignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultTimeoutUpdatedEvent {
  export type InputTuple = [oldTimeout: BigNumberish, newTimeout: BigNumberish];
  export type OutputTuple = [oldTimeout: bigint, newTimeout: bigint];
  export interface OutputObject {
    oldTimeout: bigint;
    newTimeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    result: BigNumberish,
    winner: AddressLike
  ];
  export type OutputTuple = [gameId: string, result: bigint, winner: string];
  export interface OutputObject {
    gameId: string;
    result: bigint;
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCancelledEvent {
  export type InputTuple = [gameId: BytesLike, player1: AddressLike];
  export type OutputTuple = [gameId: string, player1: string];
  export interface OutputObject {
    gameId: string;
    player1: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCompletedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    winner: AddressLike,
    winnerPayout: BigNumberish,
    platformFee: BigNumberish,
    result: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    winner: string,
    winnerPayout: bigint,
    platformFee: bigint,
    result: bigint
  ];
  export interface OutputObject {
    gameId: string;
    winner: string;
    winnerPayout: bigint;
    platformFee: bigint;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCreatedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    player1: AddressLike,
    wagerAmount: BigNumberish,
    timeoutSeconds: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    player1: string,
    wagerAmount: bigint,
    timeoutSeconds: bigint
  ];
  export interface OutputObject {
    gameId: string;
    player1: string;
    wagerAmount: bigint;
    timeoutSeconds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameDisputedEvent {
  export type InputTuple = [gameId: BytesLike, disputedBy: AddressLike];
  export type OutputTuple = [gameId: string, disputedBy: string];
  export interface OutputObject {
    gameId: string;
    disputedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameJoinedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    player2: AddressLike,
    totalPot: BigNumberish
  ];
  export type OutputTuple = [gameId: string, player2: string, totalPot: bigint];
  export interface OutputObject {
    gameId: string;
    player2: string;
    totalPot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformVaultUpdatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutClaimedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    winner: AddressLike,
    loser: AddressLike
  ];
  export type OutputTuple = [gameId: string, winner: string, loser: string];
  export interface OutputObject {
    gameId: string;
    winner: string;
    loser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasureChessEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TreasureChessEscrow;
  waitForDeployment(): Promise<this>;

  interface: TreasureChessEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_WAGER: TypedContractMethod<[], [bigint], "view">;

  MIN_WAGER: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  backendSigner: TypedContractMethod<[], [string], "view">;

  calculatePayout: TypedContractMethod<
    [totalPot: BigNumberish],
    [[bigint, bigint] & { winnerPayout: bigint; platformFee: bigint }],
    "view"
  >;

  cancelGame: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  claimTimeoutWin: TypedContractMethod<
    [gameId: BytesLike],
    [void],
    "nonpayable"
  >;

  createGame: TypedContractMethod<
    [
      gameId: BytesLike,
      wagerAmount: BigNumberish,
      timeoutSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  defaultTimeoutSeconds: TypedContractMethod<[], [bigint], "view">;

  emergencyRefund: TypedContractMethod<
    [gameId: BytesLike],
    [void],
    "nonpayable"
  >;

  games: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        gameId: string;
        player1: string;
        player2: string;
        wagerAmount: bigint;
        totalPot: bigint;
        status: bigint;
        result: bigint;
        createdAt: bigint;
        lastMoveAt: bigint;
        timeoutSeconds: bigint;
      }
    ],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BytesLike],
    [TreasureChessEscrow.GameStructOutput],
    "view"
  >;

  isTrustedForwarder: TypedContractMethod<
    [forwarder: AddressLike],
    [boolean],
    "view"
  >;

  joinGame: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  markDisputed: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  platformVault: TypedContractMethod<[], [string], "view">;

  recordMove: TypedContractMethod<
    [gameId: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueGameFunds: TypedContractMethod<
    [gameId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [gameId: BytesLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBackendSigner: TypedContractMethod<
    [_newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultTimeout: TypedContractMethod<
    [_seconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformVault: TypedContractMethod<
    [_newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResult: TypedContractMethod<
    [gameId: BytesLike, result: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  totalGamesCreated: TypedContractMethod<[], [bigint], "view">;

  totalPlatformFees: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustedForwarder: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  usedSignatures: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_WAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WAGER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "backendSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculatePayout"
  ): TypedContractMethod<
    [totalPot: BigNumberish],
    [[bigint, bigint] & { winnerPayout: bigint; platformFee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelGame"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeoutWin"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<
    [
      gameId: BytesLike,
      wagerAmount: BigNumberish,
      timeoutSeconds: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultTimeoutSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyRefund"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        gameId: string;
        player1: string;
        player2: string;
        wagerAmount: bigint;
        totalPot: bigint;
        status: bigint;
        result: bigint;
        createdAt: bigint;
        lastMoveAt: bigint;
        timeoutSeconds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BytesLike],
    [TreasureChessEscrow.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTrustedForwarder"
  ): TypedContractMethod<[forwarder: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markDisputed"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordMove"
  ): TypedContractMethod<
    [gameId: BytesLike, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueGameFunds"
  ): TypedContractMethod<
    [gameId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [gameId: BytesLike, result: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBackendSigner"
  ): TypedContractMethod<[_newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultTimeout"
  ): TypedContractMethod<[_seconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformVault"
  ): TypedContractMethod<[_newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [gameId: BytesLike, result: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalGamesCreated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPlatformFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustedForwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usedSignatures"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "BackendSignerUpdated"
  ): TypedContractEvent<
    BackendSignerUpdatedEvent.InputTuple,
    BackendSignerUpdatedEvent.OutputTuple,
    BackendSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultTimeoutUpdated"
  ): TypedContractEvent<
    DefaultTimeoutUpdatedEvent.InputTuple,
    DefaultTimeoutUpdatedEvent.OutputTuple,
    DefaultTimeoutUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "GameCancelled"
  ): TypedContractEvent<
    GameCancelledEvent.InputTuple,
    GameCancelledEvent.OutputTuple,
    GameCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GameCompleted"
  ): TypedContractEvent<
    GameCompletedEvent.InputTuple,
    GameCompletedEvent.OutputTuple,
    GameCompletedEvent.OutputObject
  >;
  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameDisputed"
  ): TypedContractEvent<
    GameDisputedEvent.InputTuple,
    GameDisputedEvent.OutputTuple,
    GameDisputedEvent.OutputObject
  >;
  getEvent(
    key: "GameJoined"
  ): TypedContractEvent<
    GameJoinedEvent.InputTuple,
    GameJoinedEvent.OutputTuple,
    GameJoinedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformVaultUpdated"
  ): TypedContractEvent<
    PlatformVaultUpdatedEvent.InputTuple,
    PlatformVaultUpdatedEvent.OutputTuple,
    PlatformVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutClaimed"
  ): TypedContractEvent<
    TimeoutClaimedEvent.InputTuple,
    TimeoutClaimedEvent.OutputTuple,
    TimeoutClaimedEvent.OutputObject
  >;

  filters: {
    "BackendSignerUpdated(address,address)": TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;
    BackendSignerUpdated: TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;

    "DefaultTimeoutUpdated(uint256,uint256)": TypedContractEvent<
      DefaultTimeoutUpdatedEvent.InputTuple,
      DefaultTimeoutUpdatedEvent.OutputTuple,
      DefaultTimeoutUpdatedEvent.OutputObject
    >;
    DefaultTimeoutUpdated: TypedContractEvent<
      DefaultTimeoutUpdatedEvent.InputTuple,
      DefaultTimeoutUpdatedEvent.OutputTuple,
      DefaultTimeoutUpdatedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint8,address)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "GameCancelled(bytes32,address)": TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;
    GameCancelled: TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;

    "GameCompleted(bytes32,address,uint256,uint256,uint8)": TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;
    GameCompleted: TypedContractEvent<
      GameCompletedEvent.InputTuple,
      GameCompletedEvent.OutputTuple,
      GameCompletedEvent.OutputObject
    >;

    "GameCreated(bytes32,address,uint256,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameDisputed(bytes32,address)": TypedContractEvent<
      GameDisputedEvent.InputTuple,
      GameDisputedEvent.OutputTuple,
      GameDisputedEvent.OutputObject
    >;
    GameDisputed: TypedContractEvent<
      GameDisputedEvent.InputTuple,
      GameDisputedEvent.OutputTuple,
      GameDisputedEvent.OutputObject
    >;

    "GameJoined(bytes32,address,uint256)": TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;
    GameJoined: TypedContractEvent<
      GameJoinedEvent.InputTuple,
      GameJoinedEvent.OutputTuple,
      GameJoinedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformVaultUpdated(address,address)": TypedContractEvent<
      PlatformVaultUpdatedEvent.InputTuple,
      PlatformVaultUpdatedEvent.OutputTuple,
      PlatformVaultUpdatedEvent.OutputObject
    >;
    PlatformVaultUpdated: TypedContractEvent<
      PlatformVaultUpdatedEvent.InputTuple,
      PlatformVaultUpdatedEvent.OutputTuple,
      PlatformVaultUpdatedEvent.OutputObject
    >;

    "TimeoutClaimed(bytes32,address,address)": TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
    TimeoutClaimed: TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
  };
}
